apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "praxis.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "praxis.labels" . | nindent 4 }}
data:
  PRAXIS_LISTEN_ADDR: "0.0.0.0:9080"
  PRAXIS_SCHEMA_DIR: "/schemas"
  AWS_REGION: {{ .Values.aws.region | quote }}
  AWS_DEFAULT_REGION: {{ .Values.aws.region | quote }}
  PRAXIS_ACCOUNT_NAME: {{ .Values.account.name | quote }}
  PRAXIS_ACCOUNT_REGION: {{ default .Values.aws.region .Values.account.region | quote }}
  PRAXIS_ACCOUNT_CREDENTIAL_SOURCE: {{ .Values.account.credentialSource | quote }}
  {{- if .Values.aws.endpointUrl }}
  AWS_ENDPOINT_URL: {{ .Values.aws.endpointUrl | quote }}
  {{- end }}
  {{- if .Values.account.roleArn }}
  PRAXIS_ACCOUNT_ROLE_ARN: {{ .Values.account.roleArn | quote }}
  {{- end }}
  {{- if .Values.account.externalId }}
  PRAXIS_ACCOUNT_EXTERNAL_ID: {{ .Values.account.externalId | quote }}
  {{- end }}
